# This files contains unicodes for non-alphanumeric characters.
# The MacOS 'Key Codes' program was used to look up the unicodes.
# Other codes not present on the mac keyboard were looked up here:
#  https://developer.apple.com/documentation/appkit/1535851-function-key_unicodes?language=objc

left: '&#xF702;'
right: '&#xF703;'
up: '&#xF700;'
down: '&#xF701;'
tab: '&#x0009;'
tabLeft: '&#x0019;'
backspace: '&#x007F;'
return: '&#x000D;'
escape: '&#x001B;'
delete: '&#x007F;'
delete_forward: '&#x007F;'
pageUp: '&#xF72C;'
pageDown: '&#xF72D;'
home: '&#xF729;'
end: '&#xF72B;'
f1: '&#xF704;'
f2: '&#xF705;'
f3: '&#xF706;'
f4: '&#xF707;'
f5: '&#xF708;'
f6: '&#xF709;'
f7: '&#xF70A;'
f8: '&#xF70B;'
f9: '&#xF70C;'
f10: '&#xF70D;'
f11: '&#xF70E;'
f12: '&#xF70F;'
f13: '&#xF710;'
f14: '&#xF711;'
f15: '&#xF712;'
f16: '&#xF713;'
f17: '&#xF714;'
f18: '&#xF715;'
f19: '&#xF716;'
f20: '&#xF717;'
f21: '&#xF718;'
f22: '&#xF719;'
f23: '&#xF71A;'
f24: '&#xF71B;'
f25: '&#xF71C;'
f26: '&#xF71D;'
f27: '&#xF71E;'
f28: '&#xF71F;'
f29: '&#xF720;'
f30: '&#xF721;'
f31: '&#xF722;'
f32: '&#xF723;'
f33: '&#xF724;'
f34: '&#xF725;'
f35: '&#xF726;'
