layers:
  numbers:
    description: "Numbers Layer"
    trigger: grave_accent_and_tilde
    mappings:
      - spacebar: 0
      - m: 1
      - comma: 2
      - period: 3
      - j: 4
      - k: 5
      - l: 6
      - u: 7
      - i: 8
      - o: 9

  navigation_plus:
    description: "Navigation Layer Plus"
    trigger: [left_command, spacebar]
    mappings:
    - j:
        key_code: left_arrow
        modifier: left_option
    - k:
        key_code: down_arrow
        modifier: left_option
    - l:
        key_code: right_arrow
        modifier: left_option
    - i:
        key_code: up_arrow
        modifier: left_option



  navigation:
    description: "Navigation Layer"
    trigger: left_command
    mappings:
      - j: left_arrow
      - k: down_arrow
      - l: right_arrow
      - i: up_arrow

      - m: return_or_enter
      - u: delete_or_backspace
      - o: delete_forward

      - description: "home"
        from: h
        to:
          key_code: left_arrow
          modifier: left_command

      - description: "end"
        from: semicolon
        to:
          key_code: right_arrow
          modifier: left_command

      - description: "forward tab"
        from: w
        to: tab

      - description: "backward tab"
        from: q
        to:
          key_code: tab
          modifier: right_shift

